"""Generate a self-contained SQL file to update wheat_psp mapping columns.

Reads panref2traescs_minimap_FINAL.tsv (or legacy 2-col tsv) and emits
psp_mapping_update.sql: adds cs_03g_id (and cs_gene_id if missing), loads the
mapping into a temporary table, and joins it into wheat_psp. Prediction columns
are untouched.

Run locally (mapping file on this machine), then import on the server:
    python3 scripts/gen_psp_mapping_sql.py mapping.tsv -o psp_mapping_update.sql
    scp psp_mapping_update.sql user@server:/tmp/
    # on server:
    mysql -uroot -p wheat_psp_db < /tmp/psp_mapping_update.sql
"""
from __future__ import annotations

import argparse
import os
import re

CHUNK = 5000


def load_mapping(path: str) -> dict:
    mapping: dict = {}
    with open(path, encoding="utf-8", errors="ignore") as f:
        first = f.readline().rstrip()
        cols = first.split("\t")
        if cols and cols[0] == "panref_id":
            cl = [c.strip().lower() for c in cols]
            i_pid, i_02 = cl.index("panref_id"), cl.index("cs_02g")
            i_03 = cl.index("cs_03g") if "cs_03g" in cl else None
            for line in f:
                row = line.rstrip().split("\t")
                if len(row) <= max(i_pid, i_02):
                    continue
                pid = row[i_pid].strip()
                g2 = row[i_02].strip()
                g3 = row[i_03].strip() if i_03 is not None and len(row) > i_03 else ""
                if pid and g2:
                    mapping[pid] = (g2, g3 or "")
        else:
            for line in f:
                parts = line.rstrip().split("\t")
                if len(parts) < 2:
                    continue
                q, s = parts[0].strip(), parts[1].strip()
                if q and s:
                    mapping[q] = (re.sub(r"\.\d+$", "", s), "")
    return mapping


def sql_str(v: str) -> str:
    return "'" + v.replace("\\", "\\\\").replace("'", "''") + "'"


def ensure_column(col: str, ddl: str) -> str:
    return (
        "SET @c := (SELECT COUNT(*) FROM information_schema.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wheat_psp' "
        f"AND COLUMN_NAME = '{col}');"
        + "\n"
        + "SET @s := IF(@c = 0, " + sql_str(ddl) + ", 'SELECT 1');"
        + "\n"
        + "PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("mapping")
    ap.add_argument("-o", "--out", default="psp_mapping_update.sql")
    ap.add_argument("--unmap-missing", action="store_true",
                    help="NULL out mapping for gene_ids absent from the file")
    args = ap.parse_args()

    mapping = load_mapping(args.mapping)
    print(f"mapping loaded: {len(mapping)} panref genes")

    out = []
    out.append("-- Auto-generated by scripts/gen_psp_mapping_sql.py")
    out.append("-- Updates wheat_psp.cs_gene_id (02G) + cs_03g_id from panref2traescs mapping.")
    out.append("-- Only mapping columns are touched; prediction columns are NOT modified.")
    out.append("")
    out.append(ensure_column("cs_gene_id",
                             "ALTER TABLE wheat_psp ADD COLUMN cs_gene_id VARCHAR(100) DEFAULT NULL, "
                             "ADD INDEX idx_cs_gene (cs_gene_id)"))
    out.append("")
    out.append(ensure_column("cs_03g_id",
                             "ALTER TABLE wheat_psp ADD COLUMN cs_03g_id VARCHAR(100) DEFAULT NULL, "
                             "ADD INDEX idx_cs_03g (cs_03g_id)"))
    out.append("")
    out.append("DROP TEMPORARY TABLE IF EXISTS tmp_wpsp_map;")
    out.append("CREATE TEMPORARY TABLE tmp_wpsp_map ("
               "gene_id VARCHAR(100) PRIMARY KEY, cs_gene_id VARCHAR(100), cs_03g_id VARCHAR(100)) ENGINE=InnoDB;")
    out.append("")
    items = list(mapping.items())
    for i in range(0, len(items), CHUNK):
        vals = ", ".join(
            "(%s, %s, %s)" % (sql_str(pid), sql_str(g2), sql_str(g3))
            for pid, (g2, g3) in items[i:i + CHUNK]
        )
        out.append("INSERT INTO tmp_wpsp_map VALUES " + vals + ";")
    out.append("")
    out.append("UPDATE wheat_psp p JOIN tmp_wpsp_map m ON p.gene_id = m.gene_id "
               "SET p.cs_gene_id = m.cs_gene_id, p.cs_03g_id = m.cs_03g_id;")
    if args.unmap_missing:
        out.append("UPDATE wheat_psp SET cs_gene_id = NULL, cs_03g_id = NULL "
                   "WHERE gene_id IS NOT NULL AND gene_id <> '' "
                   "AND gene_id NOT IN (SELECT gene_id FROM tmp_wpsp_map);")
    out.append("")
    out.append("SELECT COUNT(*) AS total, SUM(cs_gene_id IS NOT NULL) AS with_02g, "
               "SUM(cs_03g_id IS NOT NULL) AS with_03g FROM wheat_psp;")
    out.append("SELECT COUNT(DISTINCT cs_gene_id) AS distinct_02g, "
               "COUNT(DISTINCT cs_03g_id) AS distinct_03g FROM wheat_psp;")
    out.append("SELECT COUNT(DISTINCT cs_gene_id) AS lc_02g_genes "
               "FROM wheat_psp WHERE cs_gene_id LIKE '%LC';")
    text = "\n".join(out) + "\n"
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"written: {args.out} ({os.path.getsize(args.out)} bytes, {len(out)} statements)")


if __name__ == "__main__":
    main()
